### PR TITLE
Add Lanczos3 scaling

### PR DESCRIPTION
**Pull request by Splendide-Imaginarius**
Lanczos filtering tends to yield much better quality (sharper image) than bilinear filtering.

### CODE REVIEW

**Comment by Splendide-Imaginarius** [comment]
Hi @strumajen , thanks for the merge. It was suggested to me after I submitted this PR that reusing the `smoothScaling` config option (by changing it to an integer) might be preferable from an API perspective; an adjusted version of this PR that integrates that change (along with a few other changes/fixes) is at https://github.com/rainefall/mkxp-zr/pull/3 . If you'd like to use that PR instead of this one (you could revert this PR's commit and then cherry-pick that PR's commit, I think), by all means feel free.

**Comment by ghost** [comment]
I'm not entirely sure how many people would want more (I'm actually not even sure how many people switch away from Nearest) so I'm not gonna add a bunch of them yet, but I'm not averse to the option of having more so I just wanted to add this one this time

It seemed like there was also a sliver of manual labor required to get it running on macOS so I'd rather just save it for another time. I'm gonna remember it though

**Comment by Splendide-Imaginarius** [comment]
Alright, no worries. I just realized there's a bug in the shader in this PR, which causes an error on Linux (not sure why Windows and Linux drivers have different behavior). The shader fix is in the PR I linked, is it OK if I just submit a follow-up PR here that updates the shader but doesn't change anything else?

**Comment by Splendide-Imaginarius** [comment]
Actually if you fixed it for macOS, that probably also fixed it for Linux. I'll double-check on my Linux machine.

**Comment by Splendide-Imaginarius** [comment]
Can confirm the macOS fixes also fixed it for Linux, so no problem.

**Pull request merged**
