### PR TITLE
Shrink missized blits

### PR DESCRIPTION
**Pull request by WaywardHeart**
Take 2. There's hopefully no problems with this one. Without this fix, the outermost pixels of the source bitmap will get stretched to the edge of the blitted area. With it, the empty area will be transparent and the destination will keep what was originally there, which matches RPG Maker's behavior.

And a little off topic, while I was looking at bitmap.cpp I noticed we're not allowing transparent blits from mega surfaces unless subImageFix is on. Is that still necessary, or should we have the subImageFix section handle those no matter what?

### CODE REVIEW

**Comment by Splendide-Imaginarius** [comment]
Thanks, I'll try this out and see if it still fixes the bug.

**Comment by Splendide-Imaginarius** [comment]
I don't understand why the Windows CI job failed, I just restarted it in the hopes that whatever broke was a temporary glitch on GitHub's end.

**Comment by Splendide-Imaginarius** [comment]
> And a little off topic, while I was looking at bitmap.cpp I noticed we're not allowing transparent blits from mega surfaces unless subImageFix is on. Is that still necessary, or should we have the subImageFix section handle those no matter what?

That sounds like a possibly bug, feel free to open a separate issue for that.

**Comment by WaywardHeart** [comment]
Decided to use floats instead of ints, since I'm shrinking both rects to fit their targets now, and changed the function name to CamelCase since that's what most other functions are using. This should be ready to commit, unless you see a problem with the math.

**Comment by Splendide-Imaginarius** [comment]
Can you add a `customScript` test suite for this, similar to what's already in the `tests` folder? It would make it a lot easier to make sure we don't have regressions later.

**Comment by Splendide-Imaginarius** [comment]
I can confirm that this PR (as of 43ac2b35a153335cb757c950bcd8d75bf99bd054) fixes the bug in the only real-world game I have available that triggers it. Still would be good to have some automated tests though.

**Comment by Splendide-Imaginarius** [comment]
Added a test suite (roughly matches a real-world game's usage); confirmed that the test suite shows this branch passing and current `dev` failing. I will merge this as soon as the CI run passes.

**Comment by Splendide-Imaginarius** [comment]
Thanks!

**Pull request merged**
