### PR TITLE
Prevent building against incorrect sdl2_image.

### LINKED ISSUE #33: Ninja build fails with no link against libjxl. Ubuntu 23.04.
Ninja fails to build mkxp-z without linking against libjxl. If the link is manually added to the build command it completes as expected.

```
[102/102] Linking target mkxp-z.x86_64
FAILED: mkxp-z.x86_64 
c++  -o mkxp-z.x86_64 mkxp-z.x86_64.p/src_main.cpp.o mkxp-z.x86_64.p/src_config.cpp.o mkxp-z.x86_64.p/src_eventthread.cpp.o mkxp-z.x86_64.p/src_settingsmenu.cpp.o mkxp-z.x86_64.p/src_sharedstate.cpp.o mkxp-z.x86_64.p/src_audio_alstream.cpp.o mkxp-z.x86_64.p/src_audio_audio.cpp.o mkxp-z.x86_64.p/src_audio_audiostream.cpp.o mkxp-z.x86_64.p/src_audio_fluid-fun.cpp.o mkxp-z.x86_64.p/src_audio_midisource.cpp.o mkxp-z.x86_64.p/src_audio_sdlsoundsource.cpp.o mkxp-z.x86_64.p/src_audio_soundemitter.cpp.o mkxp-z.x86_64.p/src_audio_vorbissource.cpp.o mkxp-z.x86_64.p/src_theoraplay_theoraplay.c.o mkxp-z.x86_64.p/src_crypto_rgssad.cpp.o mkxp-z.x86_64.p/src_display_autotiles.cpp.o mkxp-z.x86_64.p/src_display_autotilesvx.cpp.o mkxp-z.x86_64.p/src_display_bitmap.cpp.o mkxp-z.x86_64.p/src_display_font.cpp.o mkxp-z.x86_64.p/src_display_graphics.cpp.o mkxp-z.x86_64.p/src_display_plane.cpp.o mkxp-z.x86_64.p/src_display_sprite.cpp.o mkxp-z.x86_64.p/src_display_tilemap.cpp.o mkxp-z.x86_64.p/src_display_tilemapvx.cpp.o mkxp-z.x86_64.p/src_display_viewport.cpp.o mkxp-z.x86_64.p/src_display_window.cpp.o mkxp-z.x86_64.p/src_display_windowvx.cpp.o mkxp-z.x86_64.p/src_display_libnsgif_libnsgif.c.o mkxp-z.x86_64.p/src_display_libnsgif_lzw.c.o mkxp-z.x86_64.p/src_display_gl_gl-debug.cpp.o mkxp-z.x86_64.p/src_display_gl_gl-fun.cpp.o mkxp-z.x86_64.p/src_display_gl_gl-meta.cpp.o mkxp-z.x86_64.p/src_display_gl_glstate.cpp.o mkxp-z.x86_64.p/src_display_gl_scene.cpp.o mkxp-z.x86_64.p/src_display_gl_shader.cpp.o mkxp-z.x86_64.p/src_display_gl_texpool.cpp.o mkxp-z.x86_64.p/src_display_gl_tileatlas.cpp.o mkxp-z.x86_64.p/src_display_gl_tileatlasvx.cpp.o mkxp-z.x86_64.p/src_display_gl_tilequad.cpp.o mkxp-z.x86_64.p/src_display_gl_vertex.cpp.o mkxp-z.x86_64.p/src_util_iniconfig.cpp.o mkxp-z.x86_64.p/src_util_win-consoleutils.cpp.o mkxp-z.x86_64.p/src_etc_etc.cpp.o mkxp-z.x86_64.p/src_etc_table.cpp.o mkxp-z.x86_64.p/src_filesystem_filesystem.cpp.o mkxp-z.x86_64.p/src_filesystem_filesystemImpl.cpp.o mkxp-z.x86_64.p/src_input_input.cpp.o mkxp-z.x86_64.p/src_input_keybindings.cpp.o mkxp-z.x86_64.p/src_net_LUrlParser.cpp.o mkxp-z.x86_64.p/src_net_net.cpp.o mkxp-z.x86_64.p/src_system_systemImpl.cpp.o mkxp-z.x86_64.p/binding_binding-mri.cpp.o mkxp-z.x86_64.p/binding_binding-util.cpp.o mkxp-z.x86_64.p/binding_table-binding.cpp.o mkxp-z.x86_64.p/binding_etc-binding.cpp.o mkxp-z.x86_64.p/binding_bitmap-binding.cpp.o mkxp-z.x86_64.p/binding_font-binding.cpp.o mkxp-z.x86_64.p/binding_graphics-binding.cpp.o mkxp-z.x86_64.p/binding_input-binding.cpp.o mkxp-z.x86_64.p/binding_sprite-binding.cpp.o mkxp-z.x86_64.p/binding_viewport-binding.cpp.o mkxp-z.x86_64.p/binding_plane-binding.cpp.o mkxp-z.x86_64.p/binding_window-binding.cpp.o mkxp-z.x86_64.p/binding_tilemap-binding.cpp.o mkxp-z.x86_64.p/binding_audio-binding.cpp.o mkxp-z.x86_64.p/binding_module_rpg.cpp.o mkxp-z.x86_64.p/binding_filesystem-binding.cpp.o mkxp-z.x86_64.p/binding_windowvx-binding.cpp.o mkxp-z.x86_64.p/binding_tilemapvx-binding.cpp.o mkxp-z.x86_64.p/binding_http-binding.cpp.o mkxp-z.x86_64.p/binding_miniffi-binding.cpp.o mkxp-z.x86_64.p/binding_miniffi.cpp.o -L/tmp/mkxp/src/linux/build-x86_64/lib -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 '-Wl,-rpath,$ORIGIN/../linux/build-x86_64/lib' -Wl,-rpath-link,/tmp/mkxp/src/build/../linux/build-x86_64/lib -static-libgcc -static-libstdc++ -Wl,--start-group /usr/lib/x86_64-linux-gnu/libGL.so -lcharset /tmp/mkxp/src/linux/build-x86_64/lib/libssl.a -ldl -pthread /tmp/mkxp/src/linux/build-x86_64/lib/libcrypto.a /tmp/mkxp/src/linux/build-x86_64/lib/libopenal.a /usr/lib/x86_64-linux-gnu/libsndio.so /usr/lib/gcc/x86_64-linux-gnu/12/libatomic.a -lm /usr/lib/x86_64-linux-gnu/libz.a -lbz2 /tmp/mkxp/src/linux/build-x86_64/lib/libSDL2.a -lSDL2_sound /tmp/mkxp/src/linux/build-x86_64/lib/libpixman-1.a /tmp/mkxp/src/linux/build-x86_64/lib/libphysfs.a /tmp/mkxp/src/linux/build-x86_64/lib/libtheora.a /tmp/mkxp/src/linux/build-x86_64/lib/libogg.a /tmp/mkxp/src/linux/build-x86_64/lib/libvorbisfile.a /tmp/mkxp/src/linux/build-x86_64/lib/libvorbis.a /tmp/mkxp/src/linux/build-x86_64/lib/libSDL2_ttf.a /tmp/mkxp/src/linux/build-x86_64/lib/libfreetype.a /usr/lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/libz.a /usr/lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/libbz2.a /tmp/mkxp/src/linux/build-x86_64/lib/libSDL2_image.a /tmp/mkxp/src/linux/build-x86_64/lib/libpng16.a -liconv /tmp/mkxp/src/linux/build-x86_64/lib/libuchardet.a /usr/lib/gcc/x86_64-linux-gnu/12/libstdc++.a /tmp/mkxp/src/linux/build-x86_64/lib64/libfluidsynth.a -flto -Wl,--compress-debug-sections=zlib -Wl,-rpath,/tmp/mkxp/src/linux/build-x86_64/lib /tmp/mkxp/src/linux/build-x86_64/lib/libruby.so -Wl,--end-group
/usr/bin/ld: /tmp/mkxp/src/linux/build-x86_64/lib/libSDL2_image.a(IMG_jxl.c.o): in function `IMG_InitJXL':
IMG_jxl.c:(.text+0x12): undefined reference to `JxlDecoderCreate'
/usr/bin/ld: IMG_jxl.c:(.text+0x19): undefined reference to `JxlDecoderSubscribeEvents'
/usr/bin/ld: IMG_jxl.c:(.text+0x28): undefined reference to `JxlDecoderSetInput'
/usr/bin/ld: IMG_jxl.c:(.text+0x2f): undefined reference to `JxlDecoderProcessInput'
/usr/bin/ld: IMG_jxl.c:(.text+0x3e): undefined reference to `JxlDecoderGetBasicInfo'
/usr/bin/ld: IMG_jxl.c:(.text+0x45): undefined reference to `JxlDecoderImageOutBufferSize'
/usr/bin/ld: IMG_jxl.c:(.text+0x54): undefined reference to `JxlDecoderSetImageOutBuffer'
/usr/bin/ld: IMG_jxl.c:(.text+0x5b): undefined reference to `JxlDecoderDestroy'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by ijuintekka**
As currently no pkg-config file is generated for sdl2_image, and pkg-config is the default option for meson detecting dependencies, pkg-config will fail to find sdl2_image.pc in the build's lib/pkgconfig folder and instead pull it from the locally installed packages if it exists.

Changing the dependency search method to cmake allows meson to prioritize the version of sdl2_image we are building instead.

Fixes #33

### CODE REVIEW

**Comment by Splendide-Imaginarius** [comment]
Thanks for the fix! Just two small things:

1. Could you edit the text of your PR description to say `Fixes #33` so that GitHub knows what the relationship is between the issue and the PR? This way, GitHub will automatically close the issue when the PR is merged.
2. Could you add a comment inside `meson.build` that has the same explanation that you put in your PR description, so that people reading the code several years from now can easily tell why the `method: 'cmake'` is there?

Other than that, this looks OK to merge as long as CI doesn't produce any surprises, though I probably won't be able to merge it until the ongoing macOS CI failure is fixed (should be in less than a week).

**Comment by Splendide-Imaginarius** [comment]
(Windows and Ubuntu CI are getting as far as I'd expect them to, so no problems there.)

**Comment by Splendide-Imaginarius** [comment]
Quick question before I merge this: will this interfere with the ability to use a system-installed JXL-enabled SDL_image, assuming that the user hasn't built SDL_image with mkxp-z's included Makefile? I think some users do like to use their package manager to install deps instead of the Makefile. It sounds from your description that this just fixes the prioritization, which should be fine for that, but I guess I should check with you about that before I merge it.

**Comment by ijuintekka** [comment]
> Quick question before I merge this: will this interfere with the ability to use a system-installed JXL-enabled SDL_image, assuming that the user hasn't built SDL_image with mkxp-z's included Makefile? I think some users do like to use their package manager to install deps instead of the Makefile. It sounds from your description that this just fixes the prioritization, which should be fine for that, but I guess I should check with you about that before I merge it.

It no longer finds my system installed package with my edit. So I guess it would require some sort of conditional or inclusion of a file for pkg-config. If you don't wish to include the change, that's fine, I can add it to my collection of patches instead.

**Comment by ijuintekka** [comment]
This works. Both get checked for and it works in any scenario. There's probably a more elegant way of doing it but I'm learning as I go here. Is it acceptable?

```
sdl2_image = dependency('SDL2_image', modules: ['SDL2_image::SDL2_image-static', 'SDL2_image::brotlidec-static', 'SDL2_image::brotlicommon-static', 'SDL2_image::hwy', 'SDL2_image::jxl_dec-static'], static: build_static, method: 'cmake', required: false)
if sdl2_image.found() == false
    sdl2_image = dependency('SDL2_image', modules: ['SDL2_image::SDL2_image-static', 'SDL2_image::brotlidec-static', 'SDL2_image::brotlicommon-static', 'SDL2_image::hwy', 'SDL2_image::jxl_dec-static'], static: build_static)
endif
```

**Comment by Splendide-Imaginarius** [comment]
If there's a more elegant way to do it, I can't think of one. I think this whole issue is because upstream SDL_image made a weird decision to only generate a pkg-config file if it's being built as a dynamic library. I don't understand why they did this, and it's probably worth asking them if they could change that policy, but short-term your conditional workaround seems OK to me.

**Comment by Splendide-Imaginarius** [comment]
Thanks for the fix, appreciate it! I'll ping the SDL_image devs about finding a better long-term solution, but for now this solves the problem for mkxp-z users.

**Comment by Splendide-Imaginarius** [comment]
I just checked, and SDL_image already fixed this upstream in the SDL3 branch, but for some reason (not sure why) they never backported the fix to SDL2. Given that SDL2 is in maintenance mode, I think it's very unlikely that asking them for a backport will be successful. But at least they seem to agree it's a bug, and when we eventually switch to SDL3, we'll get a fix then I guess.

**Pull request merged**
