### PR TITLE
Parse CSV - rapidcsv

### LINKED ISSUE #69: Cherry pick rapidcsv from symphony branch
These three commits:
https://github.com/mkxp-z/mkxp-z/commit/ae997bf8b7ea0e3e138190d1a0e2964d847cf100
https://github.com/mkxp-z/mkxp-z/commit/53ff3207c36d8d30a5648d5d9712cd474fd126a6
https://github.com/mkxp-z/mkxp-z/commit/6971c6435be08cfc2b74e7b464f5bfb1af233333

Additionally update rapidcsv.h
https://github.com/d99kris/rapidcsv/blob/master/src/rapidcsv.h

### PR DESCRIPTION
**Pull request by Nathan-MV**
Fixes #69, the credits all go to Struma but since he was wiped from existence the commit doesn't show him

rapidcsv has been updated to the latest version

### CODE REVIEW

**Comment by Nathan-MV** [comment]
RapidCSV is 3-4x faster than CSV gem in my tests, anyone interested in it can test it with ``System.parse_csv(File.read(filename))``

RapidCSV
image
CSV gem
image

**Comment by Splendide-Imaginarius** [comment]
(Rebuilding...)

**Comment by Splendide-Imaginarius** [comment]
1f3af9680a4076eec24b88f388c4413efdf4ec3a LGTM, will merge if CI passes.

**Comment by Splendide-Imaginarius** [comment]
Looks like this conflicts with #207. @WaywardHeart what's the preferred pattern now for passing a new `Exception` to `raiseRbExc`?

**Comment by WaywardHeart** [comment]
@Splendide-Imaginarius @Nathan-MV Use `RB_METHOD_GUARD` instead of `RB_METHOD` for the function definition, add `RB_METHOD_GUARD_END` after the block, and then just let the exception propagate to the top for the macro to handle.

**Comment by Splendide-Imaginarius** [comment]
f27018912c78e0db12279bfaa7debda3ada1e709 LGTM.

The header file in 9c3bfa6268d66afaf04d7c1cf775718795872d45 doesn't match the hash of upstream, please either use the exact file from upstream or clarify why it needs to differ.

**Comment by Nathan-MV** [comment]
> The header file in [9c3bfa6](https://github.com/mkxp-z/mkxp-z/commit/9c3bfa6268d66afaf04d7c1cf775718795872d45) doesn't match the hash of upstream, please either use the exact file from upstream or clarify why it needs to differ.

I just CTRL+C the contents of the raw header instead of replacing the file, that's why it doesn't match

**Comment by Splendide-Imaginarius** [comment]
bd6b7035a67a86592bbcc5fe301062b336dc0014 LGTM, please squash that commit into 9c3bfa6268d66afaf04d7c1cf775718795872d45 before I merge this.

**Comment by Nathan-MV** [comment]
> RapidCSV is 3-4x faster than CSV gem in my tests, anyone interested in it can test it with `System.parse_csv(File.read(filename))`

Note: ``rapidcsv::Document doc(filepath)`` can take the filepath as the first argument, which would make it 4-5x faster than the CSV gem as we wouldn't need Ruby's ``File.read(filename)``, this could be done in a follow up PR in a new method such as ``System.load_csv``

**Comment by Splendide-Imaginarius** [comment]
48955ab120bbfbbdcebf97f89be1e07f7cee0da9 LGTM, I'll merge it if CI passes.

**Comment by Splendide-Imaginarius** [comment]
Thanks!

**Pull request merged**
