### PR TITLE
Add bicubic scaling

### PR DESCRIPTION
**Pull request by Splendide-Imaginarius**

### CODE REVIEW

**Comment by Splendide-Imaginarius** [comment]
@Eblo do I need the fix from #95 in this PR too?

**Comment by Eblo** [comment]
After re-reading my commit message, I think I actually wrote the wrong thing. It should be vertex shaders that were affected by the change. Fragment shaders would declare that precision before and after that commit. The `#ifdef` keeps it from applying to vertex shaders, as originally it did not do that.

This commit, and any commit that doesn't touch vertex shaders, should not be affected by #95.

**Comment by Splendide-Imaginarius** [comment]
> After re-reading my commit message, I think I actually wrote the wrong thing. It should be vertex shaders that were affected by the change. Fragment shaders would declare that precision before and after that commit. The `#ifdef` keeps it from applying to vertex shaders, as originally it did not do that.
> 
> This commit, and any commit that doesn't touch vertex shaders, should not be affected by #95.

@Eblo Not sure I follow; #95 adds `precision highp float;` to the Lanczos3 shader, I'm trying to understand if I need to add that to the Bicubic shader too.

**Comment by Eblo** [comment]
Oh, I meant to say that my commit message says that it fixed fragment shaders, but what actually got fixed is vertex shaders.

I added the `precision highp` declaration to `lanczos3.frag` because otherwise it would fail to link after I reverted `common.h`. To know whether that's necessary in the bicubic shader, you might have to apply the change I made to `common.h` and see if the bicubic shader compiles/links correctly.

**Comment by Splendide-Imaginarius** [comment]
OK. The shader linking issue seems to only be a thing on macOS, so I'll probably need someone with a Mac to test this. I'll ask on Matrix for test results in a day or two.

**Comment by Eblo** [comment]
While I'm not sure what range of issues were previously seen on MacOS, I can say that the Lanczos3 linking issue definitely occurred on Windows for me when I reverted `common.h`. It went away after I added the precision declaration to the fragment shader.

If I remove the precision declaration from `lanczos3.frag`, the application displays the following on startup and closes immediately:

```
Program log:
Precisions of uniform 'texSizeInv' differ between VERTEX and FRAGMENT shaders.
 EventThread termination requested
RGSS thread ack'd request after 0 ms
GLSL: An error occured while linking program 'Lanczos3Shader' (vertex 'simple', fragment 'lanczos3')
```

Edit: In the process of testing to confirm this, I went ahead and tried the bicubic shader for good measure. It does in fact produce the same issue as lanczos3 with the same `texSizeInv` uniform unless I add the highp declaration. My OpenGL/GLSL knowledge isn't expert level, but I think this means the vertex shaders are defaulting to highp. This may not be a problem normally because `texSizeInv` isn't typically used in fragment shaders in mkxp-z. I'm curious if some more seasoned GL developers have better solutions in mind, or if this is the best fit.

**Comment by Splendide-Imaginarius** [comment]
@Eblo interesting. I do not see any such issue on my Windows test machine, which makes me wonder if maybe it's GPU-specific behavior. Anyway I'll take your word for it, and I'll add the fix to this shader too.

**Comment by Eblo** [comment]
I did some research. Indeed, vertex shaders do have a default precision of highp for floats. Fragment shaders require either a defined default or a per-variable precision declaration. This would explain why I saw the linking issue that I did; `texSizeInv` would be highp in the vertex shader but implicitly mediump in the fragment shader, as per the default defined in `common.h`. Though I'm not sure why you haven't seen this issue. I have made non-compliant GLSL code before that Works On My Machine:tm: but fails to compile on others.

[OpenGL ES 2.0 Specification, page 36](https://registry.khronos.org/OpenGL/specs/es/2.0/GLSL_ES_Specification_1.00.pdf)

**Comment by Splendide-Imaginarius** [comment]
@Eblo This is maybe a dumb idea, but would it be better if I stopped reusing `texSizeInv` between the vertex and fragment shaders, and instead made the Lanczos and Bicubic fragment shaders use some other variable that has the same value but is medium precision? It wouldn't be a major code change to do this, and it sounds like it might yield a performance boost?

**Comment by Eblo** [comment]
Maybe. If the results don't actually depend on the high precision information in `texSizeInv`, it should be fine.

**Comment by Splendide-Imaginarius** [comment]
@Eblo could you give this a try? My expectation is that bicubic should work everywhere that Lanczos3 does.

**Comment by Eblo** [comment]
Can confirm that it works, and indeed it does have the same single color issue as Lanczos3 if running in the same environment.

**Pull request merged**
